/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;

@SpringBootApplication
@EnableJpaRepositories(basePackages = {"authservice.repository"})
public class App {

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }

    public String getGreeting() {
        return "Hello";
    }
}
